### ISSUE TITLE
Building Go-btfs / dockerfile / image doesn't work

### ISSUE THREAD

**Issue by solipsist01** [bittorrent/go-btfs#16]
Hello.

When i git clone **https://github.com/bittorrent/go-btfs** and build the dockerfile, it seems to build successfully.
However, when i run the image, i get the following error:

I do the exact same thing for 1.6 (**https://github.com/TRON-US/go-btfs**) and that one works without any problem.

```
root@linux:/compose/btfstest# docker logs btfstest
Changing user to btfs
btfs: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory
Changing user to btfs
btfs: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory
Changing user to btfs
btfs: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory
Changing user to btfs
btfs: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory
Changing user to btfs
btfs: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory

```

My compose file looks like this:
```

version: "3.5"
services:
  btfstest:
    container_name: btfstest
    image: solipsist01/btfs2:latest
    ports:
      - 4002:4002/tcp
      - 4002:4002/udp
    environment:
      - TZ=${TZ}
      - ENABLE_WALLET_REMOTE=true
    volumes:
      - ${STORAGE}/btfs/btfstest/:/data/btfs/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ${NETWORK}
    restart: ${RESTARTPOLICY}

networks: 
  nasi:
    name: ${NETWORK}
```
